name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - "lockscreen-lockapp-fix-stop-helper-flatroot-20250902-050254.zip"
      - "lockscreen-lockapp-fix-patch88.zip"
      - ".github/workflows/android_build.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check - list repo root
        run: ls -lah

      - name: Pick project zip (auto-detect)
        id: pick
        shell: bash
        run: |
          set -e
          if [[ -f "lockscreen-lockapp-fix-stop-helper-flatroot-20250902-050254.zip" ]]; then
            zip="lockscreen-lockapp-fix-stop-helper-flatroot-20250902-050254.zip"
          elif [[ -f "lockscreen_app_project_final_updated3.zip" ]]; then
            zip="lockscreen_app_project_final_updated3.zip"
          else
            echo "❌ 未找到 zip：请把修复后的 zip 放在仓库根目录，文件名为 lockscreen_app_project_final_fixed_new.zip 或 lockscreen_app_project_final_updated.zip"
            exit 1
          fi
          echo "zip=$zip" >> "$GITHUB_OUTPUT"
          echo "Using ZIP: $zip"
          echo "—— ZIP 内容预览 ——"
          unzip -l "$zip" | head -n 50

      - name: Unzip project to workspace root
        run: |
          rm -rf app build.gradle.kts settings.gradle.kts gradle.properties gradle/ .gradle
          unzip -q "${{ steps.pick.outputs.zip }}" -d .
          echo "After unzip:"
          ls -lah

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle 8.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Build debug APK
        run: gradle assembleDebug --no-daemon

      - name: Locate APKs
        run: |
          echo "Built APKs:"
          find app/build/outputs/apk -type f -name "*.apk" -print

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            app/build/outputs/apk/debug/*.apk
