name: Android ZIP Builder (One Zip)

on:
  workflow_dispatch:
    inputs:
      zip_name:
        description: "Exact ZIP file name at repo root (e.g., lockscreen-lockapp.zip)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify ZIP exists
        shell: bash
        run: |
          set -e
          ls -la
          if [ ! -f "${{ github.event.inputs.zip_name }}" ]; then
            echo "::error::ZIP not found at repo root: ${{ github.event.inputs.zip_name }}"
            exit 1
          fi
          echo "ZIP_NAME=${{ github.event.inputs.zip_name }}" >> $GITHUB_ENV

      - name: Install tools
        run: sudo apt-get update -y && sudo apt-get install -y unzip tree python3

      - name: Unzip
        shell: bash
        run: |
          set -e
          mkdir -p workdir
          unzip -o -q "$ZIP_NAME" -d workdir
          echo "::group::Tree (first 3 levels)"
          tree -a -L 3 workdir || true
          echo "::endgroup::"

      - name: Discover Gradle roots
        shell: bash
        run: |
          set -e
          find workdir -type f \( -name settings.gradle -o -name settings.gradle.kts \) -printf "%h\n" | sort -u > roots.txt || true
          echo "=== Discovered Gradle roots ==="
          cat roots.txt || true
          if [ -s roots.txt ]; then
            ROOT=$(head -n1 roots.txt)
            echo "ROOT_DIR=$ROOT" >> $GITHUB_ENV
            echo "HAS_ROOTS=true" >> $GITHUB_ENV
          else
            echo "HAS_ROOTS=false" >> $GITHUB_ENV
          fi

      - name: Smart fallback (synthesize Gradle root when none found)
        if: env.HAS_ROOTS == 'false'
        shell: bash
        run: |
          set -e
          # find candidate Android modules (build.gradle(.kts) + AndroidManifest.xml)
          mapfile -t MODULES < <(find workdir -type f \( -name "build.gradle" -o -name "build.gradle.kts" \) -printf "%h\n" | sort -u)
          CANDIDATES=()
          for d in "${MODULES[@]}"; do
            if [ -f "$d/src/main/AndroidManifest.xml" ] || [ -f "$d/AndroidManifest.xml" ]; then
              CANDIDATES+=("$d")
            fi
          done
          if [ ${#CANDIDATES[@]} -eq 0 ]; then
            echo "::error::No settings.gradle(.kts) and no Android modules found in ZIP. Repackage including the project root."
            exit 1
          fi

          mkdir -p synth-root
          {
            echo 'rootProject.name = "synth-root"'
            echo 'pluginManagement { repositories { google(); mavenCentral(); gradlePluginPortal() } }'
            idx=0
            for d in "${CANDIDATES[@]}"; do
              echo "include(\":m${idx}\")"
              idx=$((idx+1))
            done
            idx=0
            for d in "${CANDIDATES[@]}"; do
              rel=$(python3 - <<'PY'
import os,sys
print(os.path.relpath(sys.argv[1], "synth-root"))
PY
"$d")
              echo "project(\":m${idx}\").projectDir = file(\"$rel\")"
              idx=$((idx+1))
            done
          } > synth-root/settings.gradle.kts

          cat > synth-root/build.gradle.kts <<'KTS'
plugins {}
allprojects {
  repositories { google(); mavenCentral() }
}
KTS
          echo "ROOT_DIR=synth-root" >> $GITHUB_ENV
          echo "::group::Synth-root contents"
          tree -a -L 2 synth-root || true
          echo "::endgroup::"

      - name: Detect Gradle wrapper
        shell: bash
        run: |
          set -e
          if [ -f "$ROOT_DIR/gradlew" ]; then
            chmod +x "$ROOT_DIR/gradlew"
            echo "USE_WRAPPER=true" >> $GITHUB_ENV
          else
            echo "USE_WRAPPER=false" >> $GITHUB_ENV
          fi
          echo "Using root: $ROOT_DIR"

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build (Gradle Wrapper)
        if: env.USE_WRAPPER == 'true'
        working-directory: ${{ env.ROOT_DIR }}
        run: ./gradlew assembleDebug --no-daemon

      - name: Build (Gradle 8.4 without wrapper)
        if: env.USE_WRAPPER != 'true'
        shell: bash
        run: |
          set -e
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.4
          gradle -p "$ROOT_DIR" assembleDebug --no-daemon

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: |
            ${{ env.ROOT_DIR }}/**/build/outputs/apk/**/debug/*.apk
            ${{ env.ROOT_DIR }}/**/build/outputs/apk/debug/*.apk
          if-no-files-found: warn

      - name: Upload diagnostics (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: diagnostics
          path: |
            workdir/**
            synth-root/**
            roots.txt
          if-no-files-found: warn
