name: Build Android APK (phone-only)

on:
  workflow_dispatch:   # 允許手動觴動
  push:
    branches: [ main ] # 推送到 main 自動觴動

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android build tools / platforms
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # 仓庫裏是 zip；解压后會出现 lockscreen_app/ 工程目錄
      - name: Unzip project
        run: |
          unzip -o lockscreen_app_project.zip
          ls -la
          ls -la lockscreen_app

      # 本工程不带 gradle wrapper；用官方 Gradle Action 指定版本
      - name: Setup Gradle 8.2
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2

      # 编译 Debug APK（可直接安装）
      - name: Build Debug APK
        working-directory: lockscreen_app
        run: |
          gradle :app:assembleDebug --no-daemon

      # 上传 APK 工件，便于你在手机上下载
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: lockscreen-debug-apk
          path: lockscreen_app/app/build/outputs/apk/**/debug/*.apk
