name: Build Android APK

on:
  workflow_dispatch:
  push:
    paths:
      - "quote_app.zip33"
      - "quote_app_fixed3333.zip"
      - "lockscreen-lockapp_GITHUB_READY_BUILDABLE.zip"
      - "lockscreen-lockapp_GITHUB_READY_DISABLE_OLDPKG.zip"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check - list repo root
        run: ls -lah

      # 自动识别仓库根目录中的项目 ZIP（保持你原逻辑，仅扩展可识别文件名）
      - name: Pick project zip (auto-detect)
        id: pick
        shell: bash
        run: |
          set -e
          if [[ -f "quote_app_fixed3333.zip" ]]; then
            zip="quote_app_fixed3333.zip"
          elif [[ -f "quote_app.zip33" ]]; then
            zip="quote_app.zip33"
          elif [[ -f "lockscreen-lockapp_GITHUB_READY_DISABLE_OLDPKG.zip" ]]; then
            zip="lockscreen-lockapp_GITHUB_READY_DISABLE_OLDPKG.zip"
          elif [[ -f "lockscreen-lockapp_GITHUB_READY_BUILDABLE.zip" ]]; then
            zip="lockscreen-lockapp_GITHUB_READY_BUILDABLE.zip"
          else
            echo "❌ 未找到可识别的 zip：请把修复后的 zip 放在仓库根目录，文件名建议为 lockscreen-lockapp_GITHUB_READY_DISABLE_OLDPKG.zip 或 lockscreen-lockapp_GITHUB_READY_BUILDABLE.zip"
            exit 1
          fi
          echo "zip=$zip" >> "$GITHUB_OUTPUT"
          echo "Using ZIP: $zip"
          echo "—— ZIP 内容预览（前 50 行）——"
          unzip -l "$zip" | head -n 50

      - name: Unzip project to workspace root
        run: |
          rm -rf app build.gradle* settings.gradle* gradle.properties gradle/ .gradle
          unzip -q "${{ steps.pick.outputs.zip }}" -d .
          echo "After unzip:"
          ls -lah

      # 打印 BUILD_TAG（确认这次确实用到新代码/新缓存）
      - name: Show build tag
        run: |
          echo "BUILD_TAG:"
          test -f BUILD_TAG.txt && cat BUILD_TAG.txt || echo "NO BUILD_TAG"

      # 使用 JDK 21（与 Gradle 8.4 更匹配）
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # Gradle 缓存：key 绑定 BUILD_TAG.txt，避免回灌旧缓存
      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-cache-${{ hashFiles('BUILD_TAG.txt') }}-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-cache-

      # 保留你原做法：显式使用 Gradle 8.4（可与上面 JDK 21 配合）
      - name: Set up Gradle 8.4
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.4

      - name: Make gradlew executable (if exists)
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      # 诊断：构建前打印关键源码，确认旧包路径已禁用、FSI 写法是否正确
      - name: Diagnostic — print source tree
        run: |
          echo "---- Legacy package (com.example.app) ----"
          find app/src/main/java/com/example/app -type f -name '*.kt' -print 2>/dev/null | sort || true
          echo "---- Active package (com.example.lockapp) ----"
          find app/src/main/java/com/example/lockapp -type f -name '*.kt' -print 2>/dev/null | sort || true
          echo "---- grep setFullScreenIntent ----"
          grep -RIn "setFullScreenIntent(" app/src/main/java || true

      # 先 clean 再 assemble，避免历史产物影响
      - name: Clean
        run: |
          if [ -f ./gradlew ]; then ./gradlew clean; else gradle clean; fi

      - name: Build debug APK
        run: |
          if [ -f ./gradlew ]; then ./gradlew assembleDebug --no-daemon; else gradle assembleDebug --no-daemon; fi

      - name: Locate APKs
        run: |
          echo "Built APKs:"
          find app/build/outputs/apk -type f -name "*.apk" -print

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: |
            app/build/outputs/apk/debug/*.apk
