name: Android APK Build (Fixed Zip)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip fixed zip
        run: |
          mkdir workdir
          unzip -q "lockscreen-lockapp-kiosk-v27-overloads.zip" -d workdir

      - name: List extracted files
        run: ls -R workdir

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Gradle build
        run: |
          cd workdir
          if [ -f gradlew ]; then
            chmod +x gradlew
            ./gradlew assembleDebug
          else
            gradle assembleDebug
          fi

      - name: Upload APKs
        uses: actions/upload-artifact@v3
        with:
          name: apks
          path: workdir/**/build/outputs/apk/**/*.apk
