name: Build Android APK (AutoRoot)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Locate Gradle project root (settings.gradle/.kts)
        id: findroot
        shell: bash
        run: |
          set -e
          echo "=== Repo top-level ==="
          ls -la || true
          echo "=== Search settings.gradle(.kts) ==="
          ROOT=$(git ls-files | grep -E '(^|/)(settings\.gradle(\.kts)?)$' | sed -E 's|/(settings\.gradle(\.kts)?)$||' | head -n1)
          if [ -z "$ROOT" ]; then
            ROOT=$(find . -maxdepth 6 -type f \( -name settings.gradle -o -name settings.gradle.kts \) -print0 | xargs -0 -I{} dirname {} | head -n1)
          fi
          if [ -z "$ROOT" ]; then
            echo "::error::No settings.gradle(.kts) found anywhere in repo. Commit your Android project (with settings.gradle) or move it into the repo."
            exit 1
          fi
          echo "Detected project root: $ROOT"
          echo "root=$ROOT" >> $GITHUB_OUTPUT
          echo "Contents of root:"
          ls -la "$ROOT"

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Try Gradle Wrapper
        id: trywrapper
        shell: bash
        run: |
          set -e
          ROOT="${{ steps.findroot.outputs.root }}"
          if [ -f "$ROOT/gradlew" ]; then
            chmod +x "$ROOT/gradlew"
            echo "has_wrapper=true" >> $GITHUB_OUTPUT
          else:
            echo "has_wrapper=false" >> $GITHUB_OUTPUT
          fi

      - name: Build (with Wrapper)
        if: steps.trywrapper.outputs.has_wrapper == 'true'
        working-directory: ${{ steps.findroot.outputs.root }}
        run: ./gradlew assembleDebug --no-daemon

      - name: Install Gradle (fallback) and Build
        if: steps.trywrapper.outputs.has_wrapper != 'true'
        shell: bash
        run: |
          set -e
          echo "Gradle wrapper not found, installing Gradle via SDKMAN..."
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.4
          gradle --version
          gradle -p "${{ steps.findroot.outputs.root }}" assembleDebug --no-daemon

      - name: Upload APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: |
            ${{ steps.findroot.outputs.root }}/**/build/outputs/apk/**/debug/*.apk
            ${{ steps.findroot.outputs.root }}/**/build/outputs/apk/debug/*.apk
