name: Build Android APK standard (phone-only)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android build tools / platforms
        run: |
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      # Unzip project
      - name: Unzip project
        run: |
          unzip -o lockscreen_app_project.zip
          ls -la
          ls -la lockscreen_app

      # Setup Gradle 8.2
      - name: Setup Gradle 8.2
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2

      # Build Debug APK for standard flavor
      - name: Build Debug APK
        working-directory: lockscreen_app
        run: |
          gradle :app:assembleStandardDebug --no-daemon

      # Upload APK artifact
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: lockscreen-standard-debug-apk
          path: lockscreen_app/app/build/outputs/apk/**/debug/*.apk
